// Mock data for WhoKnows Models
// This will be used for initial rendering and can be replaced with database data

export const mockModels = [
  // New Featured Models from "Home Page" Folder
  {
    id: 'n1',
    name: 'Athina',
    slug: 'athina',
    gender: 'women' as const,
    height: null,
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'International',
    bio: null,
    featured: true,
    order: 1,
    images: [{ id: 'n1-1', modelId: 'n1', imageUrl: '/models/Home Page/ATHINA/0b0623aa-aa7e-4c81-9369-2d0530c493a2.jpg', alt: 'Athina', order: 1, isPrimary: true }],
  },
  {
    id: 'n2',
    name: 'Celine',
    slug: 'celine',
    gender: 'women' as const,
    height: null,
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'International',
    bio: null,
    featured: true,
    order: 2,
    images: [{ id: 'n2-1', modelId: 'n2', imageUrl: '/models/Home Page/CELINE/IMG_1475.jpg', alt: 'Celine', order: 1, isPrimary: true }],
  },
  {
    id: 'n3',
    name: 'Elana',
    slug: 'elana',
    gender: 'women' as const,
    height: null,
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'International',
    bio: null,
    featured: true,
    order: 3,
    images: [{ id: 'n3-1', modelId: 'n3', imageUrl: '/models/Home Page/ELANA/Cover JPG.jpg', alt: 'Elana', order: 1, isPrimary: true }],
  },
  {
    id: 'n4',
    name: 'Jasmin',
    slug: 'jasmin',
    gender: 'women' as const,
    height: null,
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'International',
    bio: null,
    featured: true,
    order: 4,
    images: [{ id: 'n4-1', modelId: 'n4', imageUrl: '/models/Home Page/JASMIN/HCL_26.jpg', alt: 'Jasmin', order: 1, isPrimary: true }],
  },
  {
    id: 'n5',
    name: 'Julien',
    slug: 'julien',
    gender: 'men' as const,
    height: null,
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'International',
    bio: null,
    featured: true,
    order: 5,
    images: [{ id: 'n5-1', modelId: 'n5', imageUrl: '/models/Home Page/JULIEN/54895457647_842e5c046e_o(1).jpg', alt: 'Julien', order: 1, isPrimary: true }],
  },
  {
    id: 'n6',
    name: 'Mika',
    slug: 'mika',
    gender: 'women' as const,
    height: null,
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'International',
    bio: null,
    featured: true,
    order: 6,
    images: [{ id: 'n6-1', modelId: 'n6', imageUrl: '/models/Home Page/MIKA/0922c753-1eb5-452b-aa5f-af32a9d8f02e.jpg', alt: 'Mika', order: 1, isPrimary: true }],
  },
  {
    id: 'n7',
    name: 'Madeline',
    slug: 'madeline',
    gender: 'women' as const,
    height: null,
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'International',
    bio: null,
    featured: true,
    order: 7,
    images: [{ id: 'n7-1', modelId: 'n7', imageUrl: '/models/Home Page/MADELINE/MADELINE-5.jpg', alt: 'Madeline', order: 1, isPrimary: true }],
  },
  {
    id: 'n8',
    name: 'Triseya',
    slug: 'triseya',
    gender: 'women' as const,
    height: null,
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'International',
    bio: null,
    featured: true,
    order: 8,
    images: [{ id: 'n8-1', modelId: 'n8', imageUrl: '/models/Home Page/TRISEYA/TRISEYA (1).jpg', alt: 'Triseya', order: 1, isPrimary: true }],
  },
  {
    id: 'n9',
    name: 'Sofia',
    slug: 'sofia',
    gender: 'women' as const,
    height: null,
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'International',
    bio: null,
    featured: true,
    order: 9,
    images: [{ id: 'n9-1', modelId: 'n9', imageUrl: '/models/Home Page/SOFIA/SOFIA (1).jpg', alt: 'Sofia', order: 1, isPrimary: true }],
  },
  {
    id: 'n10',
    name: 'Laura',
    slug: 'laura',
    gender: 'women' as const,
    height: null,
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'International',
    bio: null,
    featured: true,
    order: 10,
    images: [{ id: 'n10-1', modelId: 'n10', imageUrl: '/models/Home Page/LAURA - ALDOR/LAURA-1.jpg', alt: 'Laura', order: 1, isPrimary: true }],
  },
  {
    id: 'n11',
    name: 'Megan',
    slug: 'megan',
    gender: 'women' as const,
    height: null,
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'International',
    bio: null,
    featured: true,
    order: 11,
    images: [{ id: 'n11-1', modelId: 'n11', imageUrl: '/models/Home Page/MEGAN/MEGAN (1).jpg', alt: 'Megan', order: 1, isPrimary: true }],
  },
  {
    id: 'n12',
    name: 'Parina',
    slug: 'parina',
    gender: 'women' as const,
    height: null,
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'International',
    bio: null,
    featured: true,
    order: 12,
    images: [{ id: 'n12-1', modelId: 'n12', imageUrl: '/models/Home Page/PARINA /PARINA  (1).jpg', alt: 'Parina', order: 1, isPrimary: true }],
  },
];

export const mockCampaigns = [
  {
    id: '1',
    title: 'Summer Escape 2024',
    slug: 'summer-escape-2024',
    description: 'A vibrant summer campaign featuring our top models in tropical locations. This campaign captures the essence of summer freedom and adventure.',
    client: 'Luxe Magazine',
    year: '2024',
    coverImage: '/campaigns/summer-escape-cover.jpg',
    order: 1,
    models: [{ model: mockModels[0] }, { model: mockModels[4] }, { model: mockModels[10] }],
    images: [
      { id: 'c1-1', campaignId: '1', imageUrl: '/campaigns/summer-escape-1.jpg', alt: 'Summer Escape Campaign 1', order: 1 },
      { id: 'c1-2', campaignId: '1', imageUrl: '/campaigns/summer-escape-2.jpg', alt: 'Summer Escape Campaign 2', order: 2 },
      { id: 'c1-3', campaignId: '1', imageUrl: '/campaigns/summer-escape-3.jpg', alt: 'Summer Escape Campaign 3', order: 3 },
    ],
  },
  {
    id: '2',
    title: 'Urban Edge',
    slug: 'urban-edge',
    description: 'Street style meets high fashion in this urban-inspired campaign. Bold, edgy, and unapologetically modern.',
    client: 'Vogue Asia',
    year: '2024',
    coverImage: '/campaigns/urban-edge-cover.jpg',
    order: 2,
    models: [{ model: mockModels[1] }, { model: mockModels[6] }],
    images: [
      { id: 'c2-1', campaignId: '2', imageUrl: '/campaigns/urban-edge-1.jpg', alt: 'Urban Edge Campaign 1', order: 1 },
      { id: 'c2-2', campaignId: '2', imageUrl: '/campaigns/urban-edge-2.jpg', alt: 'Urban Edge Campaign 2', order: 2 },
    ],
  },
  {
    id: '3',
    title: 'Ethereal Dreams',
    slug: 'ethereal-dreams',
    description: 'A dreamy editorial showcasing romantic and ethereal fashion. Soft lighting and flowing fabrics create a magical atmosphere.',
    client: 'Harper\'s Bazaar',
    year: '2023',
    coverImage: '/campaigns/ethereal-dreams-cover.jpg',
    order: 3,
    models: [{ model: mockModels[2] }, { model: mockModels[3] }],
    images: [
      { id: 'c3-1', campaignId: '3', imageUrl: '/campaigns/ethereal-dreams-1.jpg', alt: 'Ethereal Dreams Campaign 1', order: 1 },
      { id: 'c3-2', campaignId: '3', imageUrl: '/campaigns/ethereal-dreams-2.jpg', alt: 'Ethereal Dreams Campaign 2', order: 2 },
    ],
  },
  {
    id: '4',
    title: 'Noir Elegance',
    slug: 'noir-elegance',
    description: 'A sophisticated black and white campaign celebrating timeless elegance. Classic beauty meets contemporary style.',
    client: 'Elle Magazine',
    year: '2023',
    coverImage: '/campaigns/noir-elegance-cover.jpg',
    order: 4,
    models: [{ model: mockModels[8] }, { model: mockModels[7] }],
    images: [
      { id: 'c4-1', campaignId: '4', imageUrl: '/campaigns/noir-elegance-1.jpg', alt: 'Noir Elegance Campaign 1', order: 1 },
      { id: 'c4-2', campaignId: '4', imageUrl: '/campaigns/noir-elegance-2.jpg', alt: 'Noir Elegance Campaign 2', order: 2 },
    ],
  },
];

export const mockHeroSlides = [
  {
    id: '1',
    title: 'Discover Excellence',
    subtitle: 'International modelling agency representing the finest talent worldwide',
    imageUrl: '/hero/hero-1.jpg',
    link: '/women',
    order: 1,
    active: true,
  },
  {
    id: '2',
    title: 'New Faces 2024',
    subtitle: 'Meet our latest signings making waves in the fashion industry',
    imageUrl: '/hero/hero-2.jpg',
    link: '/men',
    order: 2,
    active: true,
  },
  {
    id: '3',
    title: 'Join Our Roster',
    subtitle: 'Apply now and start your modelling journey with us',
    imageUrl: '/hero/hero-3.jpg',
    link: '/apply',
    order: 3,
    active: true,
  },
];

export const mockClients = [
  { id: '1', name: 'Vogue', logoUrl: '/clients/vogue.svg', order: 1, active: true },
  { id: '2', name: 'Harper\'s Bazaar', logoUrl: '/clients/harpers.svg', order: 2, active: true },
  { id: '3', name: 'Elle', logoUrl: '/clients/elle.svg', order: 3, active: true },
  { id: '4', name: 'GQ', logoUrl: '/clients/gq.svg', order: 4, active: true },
  { id: '5', name: 'L\'Officiel', logoUrl: '/clients/lofficiel.svg', order: 5, active: true },
  { id: '6', name: 'Numéro', logoUrl: '/clients/numero.svg', order: 6, active: true },
];
